### **UNIVERSIDADE FEDERAL DE ITAJUBÁ**
### **Instituto de Matemática e Computação**
### **Sistemas de Informação**

--

### **SMAC03 - Grafos**

### **Tópico: 1. Introdução à Grafos**

## **Atividade 1 - Preparação do Ambiente e Dicas de Desenvolvimento**

---

**Objetivo:** Este notebook tem por objetivo apresentar a linguagem que será adotada para implementação dos algoritmos que serão abordados na disciplina. Ele pode ser usado como ambiente de desenvolvimento alternativo à IDE e ao Moodle. Contudo, visando uma maior autonomia do aluno, a recomendação é que seja utilizada uma IDE instalada localmente no seu equipamento.

Para cada enunciado a seguir implemente os códigos de modo a atender o que se pede.

---

## **Matrícula:** Número de Matrícula
## **Nome:** Nome Completo
---


## **0. Bibliotecas**

É recomendável adicionar as bibliotecas necessárias logo no início do código seguindo uma boa prática de programação além de evitar futuros problemas. **Obs**: Use a célula abaixo para as bibliotecas que forem necessárias.

**Q1.** Instale a biblioteca iGraph (https://python.igraph.org/en/stable/).

**Q2.** Importe as seguintes bibliotecas: numpy, time, math, random, igraph. Faça a montagem de uma pasta no repositório do Google Drive que contenha os *datasets* sobre grafos disponíveis no SIGAA (simples, ponte, zachary).

Mounted at /content/drive


---
## **1. Variáveis e *Strings***

**Q3.** Crie uma variável do tipo *string* que recebe um valor de entrada dado pelo usuário e retorna um valor do tipo inteiro que é o triplo do valor fornecido.

Digite um número: 3
<class 'str'>
<class 'int'> 9



**Q4.** Concatene duas *strings* dadas pela entrada do usuário e cujos caracteres estão todos em caixa baixa (minúsculos), de modo que o primeiro caracter de cada string se torne caixa alta (maiúsculo).

Digite seu primeiro nome: rafael
Digite seu último nome: frinhani
Rafael Frinhani


---
## **2. Entrada e Saída**

**Q5.** Implemente uma função que recebe como entrada o nome de um *dataset* armazenado no seu Google Drive (ex. simples, ponte, zachary), lê o respectivo arquivo .txt, atribua o conteúdo do arquivo a um objeto tipo `numpy.ndarray`, imprime na tela a respectiva matriz e o seu tipo.

Digite o nome do dataset: simples
[[0 1 0 0]
 [1 0 1 1]
 [0 1 0 1]
 [0 1 1 0]]
<class 'numpy.ndarray'>


**Q6.** Obtenha as dimensões da matriz no formato (linhas, colunas), bem como a lista com os valores constantes na sua diagonal.

(4, 4)
[0 0 0 0]


**Q7.** Usando a matriz obtida em Q5, imprima o elemento da posição [i][j] informado pelo usuário. Informe caso algum índice dado na entrada seja maior que a dimensão da matriz.

Digite a linha i desejada: 2
Digite a coluna j desejada: 3
Elemento da posição [2][3]: 1


**Q8.** Salve em um arquivo no seu Google Drive com o nome "resultado.txt", lista dos valores da diagonal da matriz obtida em Q6.

Lista salva em Arquivo!


---
## **3. Estruturas**

**Q9.** A partir da matriz, implemente uma função que constroi um dicionário. Cada chave do dicionário corresponde ao índice da linha da matriz. O valor de cada chave corresponde a uma lista com os índices das colunas associadas à linha em questão, que possuam valor maior que 0. Caso o valor da coluna seja maior que 1 deve-se repetir o índice da coluna conforme o valor (ex. a célula dada pela linha 1 e coluna 2 tem valor 4, logo, o valor 2 na lista da linha 1 precisará ser repetido 4 vezes).

{0: [1], 1: [0, 2, 3], 2: [1, 3], 3: [1, 2]}


**Q10.** Calcule o tempo total de execução da função que implementou em Q9, considerando precisão de 4 (quatro) casas decimais.

0.0001



**Q11.** Crie uma lista que armazene os valores de uma linha da matriz obtida em Q5, cujo índice da linha é dado como entrada. Imprima na tela essa lista e a sua versão invertida.

Digite a linha i desejada: 2
[0, 1, 0, 1]
[1, 0, 1, 0]


**Q12.** Considere a lista obtida em Q11 e altere o elemento que consta na posição 1 dessa lista para o valor 2.

[0, 2, 0, 1]


**Q13.** Considerando a lista obtida em Q11, inclua o elemento 5 no final dessa lista e inclua o elemento 3 na posição 1 da lista.

[0, 3, 2, 0, 1, 5]


---
## **4. Estruturas de Repetição**

**Q14.** Crie uma função que recebe um número do usuário e imprime na tela uma contagem regressiva até o valor 1. Utilize o comando `for`.

Digite um número: 10
10
9
8
7
6
5
4
3
2
1
Terminou


**Q15.** Implemente a mesma função solicitada em Q14, mas utilizando o comando `while`.

Digite um número: 10
10
9
8
7
6
5
4
3
2
1
Terminou


**Q16.** Implemente a mesma função solicitada em Q14, utilizando uma função recursiva.

Digite um número: 10
10
9
8
7
6
5
4
3
2
1
Terminou


---
## **5. Resolução de Problemas**

**Q17.** Calcule a área de uma circunferência com base no raio recebido pelo usuário. Imprima na tela o resultado.

Digite o raio da circunferência: 5
A área da circunferência é: 78.54



**Q18.** Crie um programa que recebe duas notas do usuário e retorna uma mensagem com base na aprovação ou reprovação considerando média maior ou igual a 6,0.

Digite o valor da nota 1: 4.7
Digite o valor da nota 2: 5.9
Infelizmente sua média foi 5.30 e você foi REPROVADO!!


**Q19.** Implemente uma função que recebe uma medida de ângulo em graus e retorna uma mensagem indicando o seu quadrante.

Digite o valor do ângulo em graus(0 a 360): 276
4º quadrante
